version: '3'

services:
  db:
    platform: linux/x86_64
    image: mariadb:10.4.18
    container_name: wordpress_project_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks: 
      - wordpress-network
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.1-php7.3-apache
    container_name: wordpress_project_server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    tty: true
    networks:
      - wordpress-network
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    # working_dir: /var/www/html
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
networks:
  wordpress-network:
    name: wordpress-network
    driver: bridge
volumes:
  db_data: